COMPILER = g++
FLAGS = -o
EXE = prog
SRC = *.cpp
#INCLUDE = 
LINK = -lopencv_core -lopencv_highgui

#compiling
main:
	$(COMPILER) $(FLAGS) $(EXE) $(SRC) $(LINK)
	
run:
	@echo "running the program"
	./$(EXE)

